#!/bin/sh
"export" "AWKPATH=$( dirname $0 )/include:$AWKPATH" 
"export" "LC_ALL=C"
"exec" "gawk" -f "$0" "--" "$@"

@load "fork"
@load "filefuncs"

# utility functions
@include "getopt.awk"
@include "arg.awk"
@include "stats.awk"

# subcommands
@include "calc.awk"
@include "win.awk"
@include "sum.awk"
@include "dist.awk"

# metrics: within
@include "lines.awk"
@include "miss.awk"
@include "pi.awk"
@include "tajima.awk"
@include "tajimalike.awk"
@include "a1.awk"
@include "a2.awk"
@include "segr.awk"
@include "segrcorr.awk"
@include "theta_w.awk"
@include "theta_low.awk"
@include "theta_mid.awk"
@include "theta_high.awk"

#metrics: between
@include "diff.awk"
@include "dxy.awk"
@include "fst.awk"
@include "fstwc.awk"
@include "rho.awk"
@include "nei.awk"

@namespace "piawka"

BEGIN{
help="\
    piawka v0.9.0 -- calculate pi & other population stats in VCF files \n\
    Subcommands: \n\
    \tpiawka calc -- calculate various population stats from a VCF file \n\
    \tpiawka win  -- prepare genomic windows from various sources \n\
    \tpiawka sum  -- summarize stats from calc output across regions \n\
    \tpiawka dist -- convert calc output to PHYLIP or NEXUS distance matrix"

  # Parse subcommand
  subcmd=ARGV[1]

  switch (subcmd) {
    case "calc":
      calc::run()
    case "win":
      win::run()
    case "sum":
      sum::run()
    case "dist":
      dist::run()
    default:
      print help
      if (subcmd != "") {
        print "Invalid subcommand: "subcmd > "/dev/stderr"
        exit 1
      }
      exit 0
  }
}

function assert(condition, explanation) {
  if (! condition) {
    print arg::help
    printf("Error: %s\n", explanation) > "/dev/stderr"
    exit 1
  }
}

function check_file(file,   cmd) {
  if (awk::stat(file, _) < 0) {
    print "Error: could not read file "file > "/dev/stderr"
    exit 1
  }
}
#
# Array copy func by Ed Morton @ https://stackoverflow.com/a/62179751/14993291
function copy_array(orig, copy,      i) {
  for (i in orig) {
    if (awk::isarray(orig[i])) {
      copy_array(orig[i], copy[i])
    }
    else {
      copy[i] = orig[i]
    }
  }
}
