#!/bin/sh
"export" "AWKPATH=$( dirname $0 ):$AWKPATH"
"export" "LC_ALL=C"
"exec" "gawk" "-v" "PIAWKADIR=$( dirname $0 )" -f "$0" "--" "$@" && 0 {}

@load "fork"
@load "filefuncs"

@include "getopt.awk"
@include "argparse.awk"

BEGIN{ 
  check_gawk_version()
  check_htslib()
  OFS="\t"
  usage="piawka v0.8.11\nUsage:\npiawka -g groups_tsv -v vcf_gz [OPTIONS]"
  SIGNAL_END_OF_BUFFER=SUBSEP SUBSEP SUBSEP
  summarize_blks=PIAWKADIR"/summarize_blks.awk"
  make_windows=PIAWKADIR"/make_windows.awk"
  aggregate_regions=PIAWKADIR"/aggregate_regions.awk"

  parse_arguments()
  print_header()
  configure_run()
  exit main()
}

function check_htslib(    bgzip_status, tabix_status) {
  bgzip_status = system("bgzip --version > /dev/null")
  tabix_status = system("tabix --version > /dev/null")
  if ( bgzip_status || tabix_status ) {
    print "Error: could not access dependencies: " ( bgzip_status ? "bgzip" : "" ) " " ( tabix_status ? "tabix" : "" )> "/dev/stderr"
    exit 1
  }
}
function check_gawk_version(    gawk_version) {
  gawk_version = substr(PROCINFO["version"],1,index(PROCINFO["version"],".")-1)
  if ( gawk_version < 5 ) {
    print "Error: GNU AWK v5.0.0 or above is needed to run piawka" > "/dev/stderr"
    exit 1
  }
}

function parse_arguments() {
  # add_argument args: shortopt, longopt, is_flag, description
  argparse::add_argument("1", "persite", 1, "output values for each site")
  argparse::add_argument("b", "bed", 0, "BED file with regions to be analyzed")
  argparse::add_argument("B", "targets", 0, "BED file with targets (faster for numerous small regions)")
  argparse::add_argument("g", "groups", 0, "either 2-columns sample / group table or \nkeywords \"unite\" (1 group) or \"divide\" (n_samples groups)")
  argparse::add_argument("h", "help", 1, "show this help message")
  argparse::add_argument("j", "jobs", 0, "number of parallel jobs to run")
  argparse::add_argument("l", "list", 1, "list all available statistics and exit")
  argparse::add_argument("m", "mult", 1, "use populations with multiple alleles at a site")
  argparse::add_argument("M", "miss", 0, "max share of missing GT per group at site, 0.0-1.0")
  argparse::add_argument("q", "quiet", 1, "do not output progress and warning messages")
  argparse::add_argument("R", "rand", 0, "randomly use this share of sites, 0.0-1.0")
  argparse::add_argument("s", "stats", 0, "stats to calculate, comma-separated, e.g. \"pi,dxy,fst\"; full list under `piawka -l`")
  argparse::add_argument("v", "vcf", 0, "gzipped and tabixed VCF file")
  help = usage "\n" argparse::format_help()
  getopt::Optind = 1 # start with 1st opt
  getopt::Opterr = 1 # print getopt errs
  if ( argparse::parse_args() != 0 ) { print help; return 0 }
  for(i in argparse::args) { args[i]=argparse::args[i] } # shorten args array name
  if ( args["help"] || ARGC==1 ) { print help; exit 0 }
  split("diff dxy fst fstwc pi tajima tajimalike rho watterson", _statslist, " ")
  for (i in _statslist) {
    statslist[_statslist[i]]=1
  } 
  if ( args["list"] ) {
    for (i in statslist) {
      print statslist[i]
    }
    exit 0
  }
  if ( args["stats"] ) {
    split( tolower(args["stats"]), statargs, "," )
    for (i in statargs) { 
      assert( statargs[i] in statslist, "statistic not found: "statargs[i]" (check options with piawka -l)" )
      stats[statargs[i]]=1 # make a separate stats array later to have fewer arguments 
      args[statargs[i]]=1
    }
  }

  # Some arg checks
  assert( args["vcf"] != "", "required argument: -v <file.vcf.gz>" )
  assert( ( args["groups"] != "" ), "required argument: -g <groups.tsv>" )
  if ( args["bed"] != "" ) { check_file( args["bed"] ) }
  if ( args["targets"] != "" ) { check_file( args["targets"] ) }
}

function configure_run() {
# Set default variable values, prepare index arrays and pipes

  if ( args["fst"] == 1 ) { FST="HUD" }
  if ( args["fstwc"] == 1 ) { FST="WC" }
  if ( args["miss"] == "" ) { args["miss"]=1 }
  if ( args["jobs"] > 1 && ( args["tajima"] || args["tajimalike"] ) ) {
    say("Warning: Tajima's D is (a bit) less precise in multithreaded mode due to averaging across windows")
  }
  if ( args["diff"] == 1 && args["rho"] == 1 ) {
    say("Warning: AFdiff is not reliable in multiallelic sites")
  }
  if ( args["mult"] == 1 && args["rho"] == 1 ) {
    say("Warning: rho was not meant for multiallelic sites")
  }
  PAIRWISE=( !args["nodxy"] || args["fst"] || args["fstwc"] || args["rho"] || args["diff"] )
  TAJLIKE=( args["tajima"] || args["tajimalike"] || args["watterson"] )

  if ( ( args["groups"] != "unite" ) && ( args["groups"] != "divide" ) ) {
    get_groups()
  }
  get_header()

  tmpcmd="mktemp -d piawkatmp.XXXXXXXX"
  if ( tmpcmd | getline tmpdir <= 0 ) {
    say("Error: failed to create temporary directory!")
    exit 1
  }
  close(tmpcmd)
  # We can't trap an exec'ed script but we can employ a process to clean the tmpdir after it's done:
  system( "{ while kill -0 "PROCINFO["pid"]" 2>/dev/null; do sleep 1; done; rm -r "tmpdir"; } &" )
  if ( args["jobs"]==0 ) {
    args["jobs"]=1 
  }
}

function main() {

  # Children: listen to query regions dispenser
  for ( jobnum=0; jobnum < args["jobs"]; jobnum++ ) { 
    if ( args["rand"] ) { srand( xor( systime(), PROCINFO["pid"] ) ) } # processes have different random seeds
    buffer = "cat #"jobnum
    buffers[buffer]++
    printf "" |& buffer # initialize pipe
    pid=fork()
    if ( pid>0 ) { continue } 
    close(buffer, "to") # children don't print to buffer
    bufl=0
    while ( $0 != SIGNAL_END_OF_BUFFER ) {
      curr= jobnum + args["jobs"] * (++bufl - 1)
      tmpf=tmpdir "/" curr ".tmp"
      getl=(buffer |& getline)
      if (getl <= 0) {
        print "Error: job "jobnum" did not reach end of buffer:" > "/dev/stderr"
        print $0 > "/dev/stderr"
        return getl
      }
      chr=$1
      start=$2
      end=$3
      locus=$4
      process_sites()
      # in case tmpf is empty, add a few bytes
      print SIGNAL_END_OF_BUFFER > tmpf
      close(tmpf)
    }
    close(buffer)
    return 0
  }
  
  # Parent process: dispense query regions or just scan the whole file
  bedcmd = get_bedcmd()
  bufl=0
  while ( bedcmd | getline > 0 ) {
    bufl++
    jobnum=bedline++ % args["jobs"]
    buffer="cat #"jobnum # number of pipes with regions == # jobs
    print $0 |& buffer
  }
  for (i in buffers) {
    print SIGNAL_END_OF_BUFFER |& i
    close(i, "to")
  }
  close( bedcmd )
  return 0
}

function get_bedcmd() {
  if ( args["bed"] != "" ) {
    return "cat "args["bed"]
  } else if (args["targets"] != "") {
    return aggregate_regions" "args["targets"] 
  } else {
    return make_windows" -v "args["vcf"]" -s "header_length
  }
}

# Groups file (first in command line): store lists of group members in `groups` array
function get_groups() { 
  check_file( args["groups"] )
  while ( getline < args["groups"] > 0 ) {
    if (!checked_groups) { assert(NF==2, "the groups file must contain two columns"); checked_groups=1 }
      groupmem[$1]=$2
  }
  close( args["groups"] )
}

# VCF header: assign samples to groups
function get_header() {
  cmd="tabix -H " args["vcf"]
  while ( cmd | getline > 0 ) { 
    header_length++
    if ($0 ~ /^#CHROM/ ) {

      # Assign sample positions to groups
      for (i=10; i<=NF; i++) {
        if ( args["groups"]=="unite" ) {
          groupindex[i]="all_samples"
          groups["all_samples"]++
        } else if ( args["groups"]=="divide" ) {
          groupindex[i]=$i
          groups[$i]++
        } else if ( groupmem[$i] != "" ) { 
          groupindex[i]=groupmem[$i]
          groups[groupmem[$i]]++
        }
      }
      # Assign ploidy to groups using variant calls from next line, detect mixed-ploidy groups
      if ( TAJLIKE || args["rho"] == 1 ) {
        cmd | getline
        # Count alleles for each group, then divide by number of samples
        for (i in groupindex) {
          ploidy[groupindex[i]] += ( ( p = index($i, ":") ) > 0 ? p : length($i)+1 )
        }
        for (g in groups) {
          ploidy[g] /= 2*groups[g]
        }
        if ( ploidy[g] % 1 != 0 && ( TAJLIKE || args["rho"] == 1 ) ) {
          say("Warning: mixed ploidy population "g" will give unreliable results with " ( TAJLIKE ? "Tajima's D" : "Ronfort's rho" ) )
        }
      }
      break
    }
  }
  close(cmd)
}

# Process VCF lines
function process_sites() {
  if ( locus == "" ) { locus="_" } # empty locus breaks summarize_blks.awk
  cmd = "tabix " args["vcf"] ( args["targets"]!="" ? " -T " args["targets"]:"" ) " "chr":"start+1"-"end  
  while ( cmd | getline > 0 ) {
    vcfline++

    if ( args["rand"] && ( rand() > args["rand"] ) ) { continue }

    # Process only SNPs (possibly monomorphic or multiallelic)
    # To obtain results identical to ksamuk/pixy, set $4 !~ /^[ACGT]$/ && $5 !~ /\*|,|[ACGT][ACGT]/
    if (length($4)>1) { continue } # if REF is multi-nucleotide, skip
    delete ALT
    ALT[a=0]=1

    # only consider single-char ALT that are not *
    while (x=index($5,",")) {
      a++
      if (x == 2 && substr($5,1,1)!="*") {
        ALT[a]=1
      }
      $5=substr($5,x+1)
    }
    if ( length($5) == 1 && $5 != "*" ) {
      ALT[++a]=1
    }

    if ( args["persite"] == 1 ) { 
      start=$2-1
      end=$2
    }
  
    # Reset site-specific parameters
    for (g in groups) { miss[g]=0; misind[g]=0; nalleles[g]=0; exclude[g]=0 }
    delete alleles
    delete thisnum
    delete thisden

    # Pool GT values for groups, count each state and missing data
    for (i in groupindex) {
      g=groupindex[i]
      if ( exclude[g] ) { continue }
      gtend=index( $i, ":" )
      if ( gtend==0 ) { gtend=length($i)+1 }
      for (c=1; c<gtend; c+=2) {
        al=substr($i,c,1)
        if ( al == "." ) {
          miss[g]+=gtend/2
          break
        } else {
          if ( !(al in ALT) ) { 
            exclude[g]=1
            break
          }
          alleles[g][al]++
          nalleles[g]++
        }
      }
      if ( args["groups"] == "divide" && g in alleles ) {
        calculate_within(g)
        for (g2 in alleles) {
          if ( g2 > g ) {
            calculate_between(g,g2)
          } else if ( g2 < g ) {
            calculate_between(g2,g)
          }
        }
      }
    }

    if ( args["groups"]!="divide" ) { 
      for ( g in alleles ) {
        if ( exclude[g] || ( args["miss"] < 1 && miss[g]/(miss[g]+nalleles[g]) > args["miss"] ) || ( args["mult"] != 1 && length(alleles[g]) > 2 ) ) { 
          delete alleles[g]
        }
      }
      for ( g in alleles ) {
        calculate_within( g )
      }
      if ( !PAIRWISE ) { continue }
      for ( g in alleles ) {
        for ( g2 in alleles ) {
          # Only making comparisons one way
          if (g2>g) { 
            calculate_between(g,g2)
          }
        }
      }
    }
  }
  close(cmd)
  if ( pid>0 ) { return 0 }
  if ( args["persite"] == 1 ) { return 0 }

  for (i in nUsed) {
    if ( split(i, ii, SUBSEP) == 1 ) {
      if ( args["pi"] ) {
        printOutput( i, ".", nUsed[i], "pi", num[i]["pi"], den[i]["pi"], allgeno[i], allmiss[i] )
      }
      if ( TAJLIKE && truesegr[i] ) {
        tP[i]=pinum[i]/piden[i]*nUsed[i]
        a1[i]/=truesegr[i]
        a2[i]/=truesegr[i]
        if ( args["watterson"] ) {
          printOutput( i, ".", truesegr[i], "thetaW", truesegr[i]/nUsed[i], a1[i], allgeno[i], allmiss[i] )
        }
        if ( args["tajima"] || args["tajimalike"] ) {
          if ( args["tajima"] ) { segr[i]=truesegr[i] }
          tajnum[i]= tP[i] - segr[i]/a1[i]
          tajden[i]=calcTajimaVar( segr[i], a1[i], a2[i], nalleles[i]+miss[i] )
          printOutput( i, ".", truesegr[i], args["tajima"] ? "TajD" : "TajD-like", tajnum[i], tajden[i], allgeno[i], allmiss[i] )
        }
      }
    } else {
      allgeno[i]=allgeno[ii[1]]+allgeno[ii[2]] 
      allmiss[i]=allmiss[ii[1]]+allmiss[ii[2]] 
      if ( args["dxy"] ) {
      printOutput( ii[1], ii[2], nUsed[i], "Dxy", num[i]["dxy"], den[i]["dxy"], allgeno[i], allmiss[i])
      }
      if ( args["diff"] ) {
        printOutput( ii[1], ii[2], nUsed[i], "AFdiff", num[i]["diff"], den[i]["diff"], allgeno[i], allmiss[i] )
      }
      if ( den[i]["fst"] ) { 
        printOutput( ii[1], ii[2], nUsed[i], "Fst_"FST, num[i]["fst"], den[i]["fst"], allgeno[i], allmiss[i] ) 
      }
      if ( args["rho"] == 1 && den[i]["Hs"] && den[i]["Ht"] ) { 
        Hs= num[i]["Hs"]/den[i]["Hs"]
        Ht= num[i]["Ht"]/den[i]["Ht"]
        Hsp= num[i]["Hsp"]/den[i]["Hsp"]
        Hpt= Hs + 2 * (Ht - Hs)
        num[i]["rho"]=Hpt-Hs
        den[i]["rho"]=Hpt-Hsp
        printOutput( ii[1], ii[2], nUsed[i], "rho", num[i]["rho"], den[i]["rho"], allgeno[i], allmiss[i] ) 
      }
    }
  }
  # Reset locus-specific parameters
  delete allgeno
  delete allmiss
  delete nUsed
  delete segr
  delete truesegr
  delete a1
  delete a2
  delete num
  delete den
}

END {
  if (pid>0) {
    say("Total jobs to run: "bufl + (bufl % args["jobs"] > 0 ? args["jobs"] : 0)-1"\n", 1 )
    for (f=0; f<bufl; f++) {
      tmpf=tmpdir"/"f".tmp"
      # to avoid race condition given persite, wait until the child writes to next region
      tmpfn=tmpdir"/"f+args["jobs"]".tmp"
      while ( stat(tmpfn, _) < 0 || _["size"]==0 ) {
        system("sleep 1")
      }
      say("Completed job " f, 1)
      while ( getline < tmpf > 0 ) {
        if ( $0 == SIGNAL_END_OF_BUFFER ) {
          break
        }
        if ( args["bed"] == "" && args["persite"] != 1 ) {
          print | summarize_blks
        } else {
          print
        }
      }
      close(tmpf)
      system("rm -f "tmpf)
    }
    # no need to wait since all children confirmedly written output?..
    close(summarize_blks)
  }
}

function calculate_within(g) {
  # Increment number of sites used for calculation
  nUsed[g]++
  
  # Extract allele counts of the group

  # Add to pi: probability that two randomly picked alleles differ
  # New formula below from https://pubmed.ncbi.nlm.nih.gov/36031871/
  thisnum[g]["pi"]=nalleles[g]^2
  thisden[g]["pi"]=nalleles[g]*(nalleles[g]-1)
  for ( x in alleles[g] ) { thisnum[g]["pi"]-=alleles[g][x]^2 }

  if ( TAJLIKE && length(alleles[g])==2 ) {
    truesegr[g]++
    a1[g]+=harm(nalleles[g]-1) 
    a2[g]+=harm2(nalleles[g]-1)
    if ( args["tajimalike"]==1 ) { segr[g]+=recalcS_expected( 1, nalleles[g], nalleles[g]+miss[g] ) }
  }

  if ( args["persite"] == 1 ) { 
    if ( thisden[g]["pi"] && args["pi"] ) { printOutput( g, ".", 1, "pi", thisnum[g]["pi"], thisden[g]["pi"], nalleles[g], miss[g] ) }
  } else {
      num[g]["pi"]+=thisnum[g]["pi"]
      den[g]["pi"]+=thisden[g]["pi"] 
      allmiss[g]+=miss[g]
      allgeno[g]+=nalleles[g]
  }
}

function calculate_between(g,g2) {
  # Is the union of allelic states from g1 and g2 bigger than length(alleles[g1])?
  poolsize=length(alleles[g])

  # Extract alleles of the group
  delete bothalleles
  for (xx in alleles[g]) {
    bothalleles[xx]++
  }
  for (yy in alleles[g2]) {
    if ( !(yy in bothalleles) ) { 
      poolsize++
      bothalleles[yy]++ # so far keeps alleles from comparisons of g with previous groups
    }
  }

  # If not args["mult"] == 1, proceed only if common allele pool has <=2 alleles
  if ( args["mult"] != 1 && poolsize > 2 ) { return 1 }

  # Increment number of sites used for dxy
  nUsed[g,g2]++
  
  # Add to dxy: probability that two alleles picked from two groups differ
  # subtraction rather than addition inspired by https://pubmed.ncbi.nlm.nih.gov/36031871/
  thisnum[g,g2]["dxy"]=nalleles[g]*nalleles[g2]
  thisden[g,g2]["dxy"]=thisnum[g,g2]["dxy"]
  if ( FST ) { 
    thisnum[g,g2]["fst"]=""
    thisden[g,g2]["fst"]="" 
  }
  for ( x in bothalleles ) { 
    # gawk breaks here if you don't set uninitialized array elems to 0
    if ( !(x in alleles[g]) ) { alleles[g][x]=0 }
    else if ( !(x in alleles[g2]) ) { alleles[g2][x]=0 }
    thisnum[g,g2]["dxy"]-=alleles[g][x]*alleles[g2][x]
    if ( args["diff"] ) { 
      thisnum[g,g2]["diff"]=alleles[g][x]*nalleles[g2] - alleles[g2][x]*nalleles[g]
      thisnum[g,g2]["diff"]*=(thisnum[g,g2]["diff"] >= 0 ? 0.5 : -0.5 )
      thisden[g,g2]["diff"]=thisden[g,g2]["dxy"]
    }
    if ( FST ) {
      if ( FST=="HUD" ) { 
        incrementFstHudson( alleles[g][x], alleles[g2][x], nalleles[g], nalleles[g2] )
      } else if ( FST=="WC" ) { 
        incrementFstWeirCockerham( alleles[g][x], alleles[g2][x], nalleles[g], nalleles[g2] )
      } 
      if ( args["mult"] != 1 ) { break } # no need to increment twice for biallelic comparisons
    }
  }
  if ( args["rho"] ) {
    # Here Hs = average of pi values of two populations,
    #      Ht = pi of two populations pooled,
    #      Hsp = Hs corrected for ploidy
    thisnum[g,g2]["Ht"]=(nalleles[g] + nalleles[g2])^2
    thisden[g,g2]["Ht"]=(nalleles[g] + nalleles[g2]) * (nalleles[g] + nalleles[g2] - 1)
    for ( x in bothalleles ) { 
      thisnum[g,g2]["Ht"]-=(alleles[g][x]+alleles[g2][x])^2 
    }
    thisnum[g,g2]["Hs"] = ( ( thisnum[g]["pi"]*thisden[g2]["pi"] ) + ( thisnum[g2]["pi"] * thisden[g]["pi"] ) )
    thisden[g,g2]["Hs"] = 2 * thisden[g]["pi"] * thisden[g2]["pi"] # same as Hspden
    thisnum[g,g2]["Hsp"] = ( ( thisnum[g]["pi"] * thisden[g2]["pi"] * ( ploidy[g] - 1 ) / ploidy[g] ) + ( thisnum[g2]["pi"] * thisden[g]["pi"] * (ploidy[g2]-1) / ploidy[g2] ) )
    thisden[g,g2]["Hsp"] = thisden[g,g2]["Hs"]
  }
  if ( args["persite"] == 1 ) { 
    if ( thisden[g,g2] && args["dxy"] ) { printOutput( g, g2, 1, "Dxy", thisnum[g,g2]["dxy"], thisden[g,g2]["dxy"], nalleles[g]+nalleles[g2], miss[g]+miss[g2] ) }
    if ( thisden[g,g2] && args["diff"] ) { printOutput( g, g2, 1, "AFdiff", thisnum[g,g2]["diff"], thisden[g,g2]["diff"], nalleles[g]+nalleles[g2], miss[g]+miss[g2] ) }
    if ( FST && thisfstden ) { printOutput( g, g2, 1, "Fst_"FST, thisnum[g,g2]["fst"], thisden[g,g2]["fst"], nalleles[g]+nalleles[g2], miss[g]+miss[g2] ) }
    if ( args["rho"] == 1 ) { 
      Hs = thisnum[g,g2]["Hs"]/thisden[g,g2]["Hs"]
      Ht = thisnum[g,g2]["Ht"]/thisden[g,g2]["Ht"]
      Hsp= thisnum[g,g2]["Hsp"]/thisden[g,g2]["Hsp"]
      Hpt= Hs + 2 * (Ht - Hs)
      thisnum[g,g2]["rho"]=Hpt-Hs
      thisden[g,g2]["rho"]=Hpt-Hsp
      printOutput( g, g2, 1, "Rho", thisnum[g,g2]["rho"], thisden[g,g2]["rho"], nalleles[g]+nalleles[g2], miss[g]+miss[g2] ) 
    }
  } else {
      num[g,g2]["diff"]+=thisnum[g,g2]["diff"]
      den[g,g2]["diff"]+=thisden[g,g2]["diff"]
      num[g,g2]["dxy"]+=thisnum[g,g2]["dxy"]
      den[g,g2]["dxy"]+=thisden[g,g2]["dxy"] 
      if ( FST ) { 
        num[g,g2]["fst"]+=thisnum[g,g2]["fst"]
        den[g,g2]["fst"]+=thisden[g,g2]["fst"]
      }
      if ( args["rho"] == 1 ) {
        num[g,g2]["Ht"] += thisnum[g,g2]["Ht"] 
        den[g,g2]["Ht"] += thisden[g,g2]["Ht"] 
        num[g,g2]["Hs"] += thisnum[g,g2]["Hs"] 
        den[g,g2]["Hs"] += thisden[g,g2]["Hs"] 
        num[g,g2]["Hsp"] += thisnum[g,g2]["Hsp"] 
        den[g,g2]["Hsp"] += thisden[g,g2]["Hsp"] 
      }
  }
}

function printOutput( pop1, pop2, nUsed, metric, numerator, denominator, nGeno, nMiss ) {
  out=chr"\t"start"\t"end"\t"locus"\t"pop1"\t"pop2"\t"nUsed"\t"metric"\t"numerator/denominator"\t"numerator"\t"denominator"\t"nGeno"\t"nMiss
  print out > tmpf
}

function harm( n ) {
 # Return Nth harmonic number
 if ( n == 0 ) { return 0 }
 if ( !(n in _harm) ) { _harm[n]= 1/n + harm(n-1) }
 return _harm[n]
}

function harm2( n ) {
 # Return Nth second harmonic number
 if ( n == 0 ) { return 0 }
 if ( !(n in _harm2) ) { _harm2[n]= 1/n^2 + harm2(n-1) }
 return _harm2[n]
}

function incrementFstHudson( a1, a2, n1, n2 ) {
  pi1 = a1 * (n1 - a1) / (n1*(n1-1))
  pi2 = a2 * (n2 - a2) / (n2*(n2-1))
  hw = pi1 + pi2
  hb = ( a1 * (n2-a2) + a2*(n1-a1) ) / (n1*n2)
  thisfstnum+=hb-hw
  thisfstden+=hb
} 

function incrementFstWeirCockerham( a1, a2, n1, n2 ) {
  # Formula from Bhatia et al. 2013, eq. (6)
  sizes = n1 * n2 / ( n1 + n2 )
  frac = 1 / ( n1 + n2 - 2 )
  mism = a1 * ( 1 - a1 / n1 ) + a2 * ( 1 - a2 / n2 )

  den = sizes * ( a1 / n1 - a2 / n2 )^2 + ( 2 * sizes - 1 ) * frac * mism
  if ( ! den ) { return } # WC Fst is NaN at uniform sites
  thisfstnum += den - 2 * sizes * frac * mism
  thisfstden += den
}

# Tajima's D-like statistic calculation
# The formula below is classic Tajima's D but with missing data we calculate a1 and a2 in a slightly different way
function calcTajimaVar( S, a1, a2, n ) {
  b1=(n+1)/(3*n-3)
  b2=(2*(n^2+n+3))/(9*n*(n-1))
  c1=b1-1/a1
  c2=b2-(n+2)/(a1*n)+a2/(a1^2)
  e1=c1/a1
  e2=c2/(a1^2+a2)
  return sqrt(e1*S + e2*S*(S-1))
}

function recalcS_expected(S, n1, n2,    coef1, coef2 ) {
  for (i=1; i<n1; i++) { coef1+=(1/i+1/(n1-i)) }
  for (i=1; i<n2; i++) { coef2+=(1/i+1/(n2-i)) }
  return S*(coef2/coef1)
}

function assert(condition, explanation) {
  if (! condition) {
    print help
    printf("Error %s:%d: %s\n",
           FILENAME, FNR, explanation) > "/dev/stderr"
    exit 1
  }
}

function print_header() {
    print "#chr", "start", "end", "locus", "pop1", "pop2", "nUsed", "metric", "value", "numerator", "denominator", "nGeno", "nMiss"
}

function check_file(file,   cmd) {
   if (stat(file, _) < 0) {
        print "Error: could not read file "file > "/dev/stderr"
        exit 1
    }
}

function say(string, same_line) {
  if (args["quiet"]) { return }
  if (same_line) {
    printf "\033[2K\r" string > "/dev/stderr"
  } else {
    print string > "/dev/stderr"
  }
}
